sudo: required
services:
  - docker

before_install:
  - docker build -t michelgrigory/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true michelgrigory/react-test npm test

after_success:
  - docker build -t michelgrigory/multi-client ./client
  - docker build -t michelgrigory/multi-nginx ./nginx
  - docker build -t michelgrigory/multi-server ./server
  - docker build -t michelgrigory/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push michelgrigory/multi-client
  - docker push michelgrigory/multi-nginx
  - docker push michelgrigory/multi-server
  - docker push michelgrigory/multi-worker
